default_stages: [commit]
repos:
- repo: local
  hooks:
  - id: tailing-whitespace
    name: Trim trailing whitespace
    entry: trailing-whitespace-fixer
    language: python
    types: [text]
  - id: end-of-file
    name: Cleanup empty lines
    entry: end-of-file-fixer
    language: python
    types: [text]
  - id: format
    name: formating
    entry: make fmt
    language: system
    types: [python]
  - id: linting
    name: Linting
    entry: make linting
    language: system
    types: [python]
  - id: typing
    name: Ttpe Checkings
    entry: make type-checkings
    language: system
    types: [python]
